Fix typos
ged/ruby-pg pull request #566
Opened 2024-04-26 06:57 UTC by kianmeng

Found via `codespell -L te,wronly,noes,nulll` and `typos --format brief`

2024-04-26 07:14 UTC, larskanis requested changes

2024-04-26 07:14 UTC, larskanis commented on lib/pg/basic_type_registry.rb
> -		[:encoder, :decoder].each do |ende|
`ende` means encoder-decoder in this context. It is no spelling mistake.

2024-04-26 07:15 UTC, larskanis commented
Thank you very much for scanning and correction! It's all OK with the exception of ende->end.

2024-04-26 07:27 UTC, merged

2024-04-26 07:27 UTC, larskanis commented
Nice - thank you!

2024-04-26 12:01 UTC, cbandy commented on lib/pg/basic_type_registry.rb
> +		# The key of these hashes maps to the `typname` column from the table pg_type.
Suggest: hash

2024-04-26 15:24 UTC, larskanis commented on ext/pg.c
> +	 * The SQLSTATE code identities the type of error that has occurred; it can be used by front-end applications to perform specific operations (such as error handling) in response to a particular data
Agreed.

2024-04-27 15:40 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: